import Head from "next/head";

async function queryAddItem() {
	const response = await fetch("/api/addPage", {
		method: "POST",
		cache: "no-cache",
		headers: {
			"Content-Type": "application/json",
		},
		body: JSON.stringify({
			text: "HELLO",
		}),
	});
	const result = await response.json();
	console.log(result);
}

async function updateDB() {
	const response = await fetch("/api/retrievePage", {
		method: "POST",
		cache: "no-cache",
		headers: {
			"Content-Type": "application/json",
		},
	});

	const result = await response.json();
	console.log(result);
}

async function testDB() {
	const response = await fetch("/api/testDB", {
		method: "POST",
		cache: "no-cache",
		headers: {
			"Content-Type": "application/json",
		},
	});

	const result = await response.json();
	console.log(result);
}

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>sdf</div>
			<button onClick={() => queryAddItem()}>Submit</button> <br />
			<button onClick={() => updateDB()}>Try update DB</button> <br />
			<button onClick={() => testDB()}> Test DB </button> <br />
			<input></input>
		</>
	);
}
